### ISSUE TITLE
Type incompatibility between behaviors

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/gen-typescript-declarations#103]
This is an issue extracted from #79 to discuss potential solutions.

The problem is the type for `value` as defined in both https://github.com/PolymerElements/iron-checked-element-behavior/blob/4d7166929e9a8da93fe83ef56fda0c01c88871c0/iron-checked-element-behavior.html#L58 and https://github.com/PolymerElements/iron-range-behavior/blob/debaca9fc5690be95982e88b3014fe9d34236203/iron-range-behavior.html#L29

When these behaviors are mixed (happens in `paper-slider` and `iron-list` for example), TypeScript reports that `string|null|undefined` is incompatible with `number|null|undefined` and will not compile.

I think we have a couple of options:

1. Remove the `type` from these behaviors. I am not sure what the impact of this change is, as this changes the way attributes are parsed in Polymer and thus might be a breaking change.
1. Make it possible to override these types in the JSDoc
1. Make it possible to override these types in `gen-tsd.json` with some way to make this unique
1. Automatically detect this issue and resort to the union of these types. (I am not sure if this is worth the effort of rewriting a whole lot of code to also do this kind of analysis)

**Comment by 43081j** [comment]
`IronFormElementBehavior` should probably have its `value` set to `Object` rather than string and produce declarations with `any`. Seems its the common base to a few elements and is often overridden.

Things like `IronRangeBehavior` are fine as is, they want their own `value` type so why not. As long as the common base these all share is open enough, it should be fine.

**Comment by TimvdLippe** [comment]
I just tried it out and setting `IronFormElementBehavior.value` to `any` does not solve the problem. The compiler will keep on complaining that `any` and `number|null|undefined` are not the same type :cry:

**Comment by 43081j** [comment]
Are you certain about that?

This compiles in ts:

```ts
interface Foo {
  x: any;
}

interface Bar extends Foo {
  x: number;
}
```

can you give a reproduction/example in ts playground maybe of what you saw/tried?

**Comment by TimvdLippe** [comment]
@43081j Like this:

```ts
interface One {
  value: string;
}

interface Two {
  value: any;
}

interface Foo extends One, Two {
}
```

Throws the following error:

```
foo.ts(9,11): error TS2320: Interface 'Foo' cannot simultaneously extend types 'One' and 'Two'.
  Named property 'value' of types 'One' and 'Two' are not identical.
```

**Comment by 43081j** [comment]
ah yeah now i see :/

you could redeclare it in the child interface:

```ts
interface Foo extends One, Two {
  value: string;
}
```

ts doesn't know which of the two you want to inherit because of multiple inheritance i guess.

If `Foo` inherited `Two`, which inherited `One`, it would work too. But we can't do that here.

**Comment by TimvdLippe** [comment]
@43081j Ah that is correct, that works :tada:

**Comment by 43081j** [comment]
awesome.

so maybe we don't need to change the type to `any` in form element. but instead just declare _which one_ in the child.

**Comment by TimvdLippe** [comment]
There were 2 other elements affected by this issue. I went through all dependencies of `iron-form-element-behavior` (https://github.com/search?l=JSON&q=org%3APolymerElements+iron-form-element-behavior&type=Code) and fixed up these elements. All other elements already had the correct definition of `value` in their respective concrete subclass.

**Comment by TimvdLippe** [comment]
All elements should now have been fixed and compiling cleanly.
