### ISSUE TITLE
Add HTMLElementTagNameMap interface

### ISSUE THREAD

**Issue by e111077** [Polymer/gen-typescript-declarations#90]
Would really like for `document.createElement('paper-input')` to return type `PaperInputElement` instead of `HTMLElement`. This is defined in the following mapping:

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L14867

This means it's possible to define just

```
interface HTMLElementTagNameMap {
  ${tagName}: ${className}
}
```

in each element declaration file and that should solve those problems. (don't worry about HTMLSlotElement, I had a PR merged into the TS toolchain that should merge into TS soon)

**Comment by aomarks** [comment]
We actually already do this. Pretty nice feature of TS.

https://github.com/Polymer/gen-typescript-declarations/blob/e962db3c781d45e9502c685d7f736eb72af03ce1/src/gen-ts.ts#L346

https://github.com/PolymerElements/iron-location/blob/2ea42b87dbfa476d38379d6bfdae032cfc4af0a9/iron-location.d.ts#L123

**Comment by e111077** [comment]
O NAISE
